### ISSUE TITLE
How to sort type exports?

### ISSUE THREAD

**Issue by jlarmstrongiv** [mskelton/eslint-plugin-sort#29]
I have an `index.ts` file where I export:

```ts
export { getArbitraryFunction } from "./getArbitraryFunction";
export type { GetArbitraryFunctionInput } from "./getArbitraryFunction"
```

but it could also look like:

```ts
export type { GetArbitraryFunctionInput } from "./getArbitraryFunction"
export { getArbitraryFunction } from "./getArbitraryFunction";
```

How can I make it so that the type imports/exports are always second (but are still grouped together by file)?

**Comment by mskelton** [comment]
This is not currently possible, though it is something I would like to improve.  I'd also like to explore the possibility of making type exports all grouped together after all the normal imports via a configuration setting.

**Comment by jlarmstrongiv** [comment]
I like it 😄 I think it would apply to sorting type imports as well

**Comment by mskelton** [comment]
@jlarmstrongiv I was thinking a little more about this and have some ideas of what the options might look like.

I'm thinking of 1-2 options. The first would be a new source group for type exports. This way you could combine all type exports into a single sort group.

```json
{
  "sort/exports": [
    "warn",
    {
      "groups": [
        { "type": "default", "order": 2 },
        { "type": "type", "order": 3 },
        { "type": "other", "order": 1 }
      ]
    }
  ]
}
```

The other option would be the type export placement. This would apply **only** if you don't use `type` as a sort group.


```json
{
  "sort/exports": [
    "warn",
    {
      "groups": [
        { "type": "default", "order": 2 },
        { "type": "other", "order": 1 }
      ],
      "typeOrder": "keep" | "before" | "after"
    }
  ]
}
```

With the `typeOrder` option you could sort type exports before or after the related export, or with `keep` it would maintain the original order. I would say the default should be `after`.

**Comment by mskelton** [comment]
I didn't think `"typeOrder: "before"` would be that useful, so sounds like it would be good as an option. Though individual type import/exports is a feature, I want to ensure the more classic way of structuring type imports/exports works. I also need to add some tests to make sure that individual type imports/exports sort properly.

**Comment by mskelton** [comment]
@jlarmstrongiv I've added the two new options that make sorting type imports/exports in https://github.com/mskelton/eslint-plugin-sort/releases/tag/v2.10.0. There is a new `type` sort group to sort type imports/exports totally separately and also a new `typeOrder` property that you can use to order types first, last, or preserve their order when they are sorted alongside of their corresponding imports/exports.

**Comment by jlarmstrongiv** [comment]
Thank you @mskelton 🎉
