### ISSUE TITLE
sort/string-unions gives false failure.  --fix is not able to fix

### ISSUE THREAD

**Issue by slalomzacharyd** [mskelton/eslint-plugin-sort#59]
For the string,

```
type ReferrerPolicy =
  "no-referrer-when-downgrade" | "no-referrer" | "origin-when-cross-origin" | "origin" | "same-origin" | "strict-origin-when-cross-origin" | "strict-origin" | "unsafe-url";
```

eslint outputs the error `warning| sort/string-unions: String unions should be sorted alphabetically.`.

My configuration is `"sort/string-unions": "warn"`.  eslint fix is unable to fix the issue.

<img width="898" alt="Screenshot 2023-12-11 at 10 38 15" src="https://github.com/mskelton/eslint-plugin-sort/assets/4054181/33e57694-1e05-427d-8072-c8806a057b33">

<img width="864" alt="Screenshot 2023-12-11 at 10 41 31" src="https://github.com/mskelton/eslint-plugin-sort/assets/4054181/40d3b9d4-8883-4ad6-8821-19db2a49ff8b">

**Comment by mskelton** [comment]
I'm unable to reproduce this. Can you make a codesandbox or reproduction repo?

**Comment by slalomzacharyd** [comment]
Sure

**Comment by mskelton** [comment]
Closing due to lack of response
