### ISSUE TITLE
[Bug] Flat config: Unable to resolve path BY 'eslint-plugin-import'

### ISSUE THREAD

**Issue by LatenPath** [mskelton/eslint-plugin-sort#60]
![image](https://github.com/mskelton/eslint-plugin-sort/assets/145383056/b7bfd266-5c48-4000-94cc-2480f6c881f0)

The plugin still works fine. Just the error message a little confused. 

I know this error cause by Import-plugin, but I hope that I can solve this issue instead of disable lint.

Thank you so much for amazing plugin!

**Comment by mskelton** [comment]
This is definitely an issue with eslint-plugin-import. This comment provides some detail:

https://github.com/import-js/eslint-plugin-import/issues/2620#issuecomment-1365459989

I'm not interested in changing the sort plugin to workaround a shortcoming of eslint-plugin-import, so I will be closing this issue as not planned.
