### ISSUE TITLE
Support computed properties for sort/object-properties and sort/type-properties

### ISSUE THREAD

**Issue by jaketodaro** [mskelton/eslint-plugin-sort#65]
Would it be possible to support sorting computed properties in objects and types? I would expect computed properties to be sorted not by their computed value, but just alphabetically by the code in the computed expression.

```
enum SomeEnum {
    foo = 'foo',
    bar = 'bar'
}

const myMap: Record<SomeEnum, string> = {
    // sort these keys?
    [SomeEnum.foo]: 'foo thing',
    [SomeEnum.bar]: 'bar thing'
}
```

**Comment by mskelton** [comment]
I'm waffling on this TBH. I can see the value, just not sure if I like it or not.

**Comment by jaketodaro** [comment]
Your call. I switched to `eslint-plugin-perfectionist` for this feature

**Comment by mskelton** [comment]
Going to close this as a won't do
